stages:
  - stage

deploy:
  tags:
    - ained
  stage: stage
  script:
    - sudo apt install -y gnupg2 pass
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t automatedtestingservice/python-tester:latest .
    - docker pull automatedtestingservice/arete:latest
    - docker run --entrypoint "sh -c chmod +x mvnw && ./mvnw test" automatedtestingservice/arete:latest
    - docker push automatedtestingservice/python-tester:latest
  only:
    - master
