stages:
  - stage

deploy:
  tags:
    - ained
  stage: stage
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t automatedtestingservice/python-tester:latest .
    - docker pull automatedtestingservice/arete:latest
    - docker-compose -f docker-compose-tests.yml up
    - docker push automatedtestingservice/python-tester:latest
  only:
    - master
