variables:
  DOCKER_DRIVER: overlay


stages:
  - deploy

deploy:
  tags:
    - docker
  image: misterio92/ci-php-node:4.0
  stage: test
  services:
    - name: docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t automatedtestingservice/python-tester:latest .
    - docker pull automatedtestingservice/arete:latest
    - docker run --entrypoint "sh -c chmod +x mvnw && ./mvnw test" automatedtestingservice/arete:latest
    - docker push automatedtestingservice/python-tester:latest
  only:
    - dev
    - master
