stages:
  - stage

deploy:
  tags:
    - ained
  stage: stage
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t automatedtestingservice/python-tester:latest .
    - docker pull automatedtestingservice/arete:latest
    - docker-compose -f docker-compose-tests.yml up --build --force-recreate --no-deps --abort-on-container-exit
    - docker push automatedtestingservice/python-tester:latest
    - curl -X POST "https://cs.ttu.ee/services/arete/api/v2/course/python-tester" -H "accept: */*" -H "X-Docker-Token: $ARETE_TOKEN"
  only:
    - master
