FROM automatedtestingservice/arete:latest

MAINTAINER enrico.vompa@gmail.com

# Tests are run using envomp gitlab account
ARG GIT_USERNAME
ENV GIT_USERNAME=$GIT_USERNAME

ARG GIT_PASSWORD
ENV GIT_PASSWORD=$GIT_PASSWORD

ARG BACKEND_URL
ENV BACKEND_URL=$BACKEND_URL

# Ignore LFS
RUN git config --global filter.lfs.smudge "git-lfs smudge --skip"

ENTRYPOINT [ "sh", "-c", "service postfix start && chmod +x mvnw && ./mvnw -Dtest=SubmissionControllerTest test" ]

EXPOSE 8098:8098
