FROM automatedtestingservice/arete:latest

MAINTAINER enrico.vompa@gmail.com

# Tests are run using envomp gitlab account
ARG GIT_USERNAME
ENV GIT_USERNAME=$GIT_USERNAME

ARG GIT_PASSWORD
ENV GIT_PASSWORD=$GIT_PASSWORD

ENTRYPOINT [ "sh", "-c", "service postfix start && chmod +x mvnw && ./mvnw test" ]

EXPOSE 8098:8098
